/**
 * Client-generated id constructors.
 *
 * Design requirement 3: every InventoryEvent carries an EventId generated by
 * the client at creation time (WP-17's outbox dedupes retried appends by
 * this id). Purchase events likewise mint a new LotId client-side, and plan
 * slots created by the generator or by hand mint a new PlanSlotId
 * client-side — Sheets has no auto-increment to hand identity out.
 *
 * IngredientId/RecipeId can equally be minted here (e.g. for a manually
 * added catalog entry) or built from a human-readable slug by whichever
 * WP creates them (WP-11 bootstrap, WP-16 seed catalog, WP-20 recipe/catalog
 * UI) — both are valid `IngredientId`/`RecipeId` values, this module does
 * not mandate one strategy.
 *
 * Uses only the injected Rng (design requirement 6) — never Math.random().
 */
import type { Rng } from "./contracts.ts";
import {
  makeEventId,
  makeIngredientId,
  makeLotId,
  makePlanSlotId,
  makePriceObservationId,
  makeProductId,
  makeRecipeId,
  makeStepId,
  type EventId,
  type IngredientId,
  type LotId,
  type PlanSlotId,
  type PriceObservationId,
  type ProductId,
  type RecipeId,
  type StepId,
} from "./types.ts";

const ID_ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz";

/** Opaque random id string, drawn from the injected Rng — deterministic under a seeded Rng. */
export function randomIdString(rng: Rng, length = 24): string {
  let out = "";
  for (let i = 0; i < length; i += 1) {
    const index = Math.floor(rng.next() * ID_ALPHABET.length);
    out += ID_ALPHABET.charAt(index);
  }
  return out;
}

export function newEventId(rng: Rng): EventId {
  return makeEventId(randomIdString(rng));
}

export function newLotId(rng: Rng): LotId {
  return makeLotId(randomIdString(rng));
}

export function newPlanSlotId(rng: Rng): PlanSlotId {
  return makePlanSlotId(randomIdString(rng));
}

export function newIngredientId(rng: Rng): IngredientId {
  return makeIngredientId(randomIdString(rng));
}

export function newRecipeId(rng: Rng): RecipeId {
  return makeRecipeId(randomIdString(rng));
}

export function newStepId(rng: Rng): StepId {
  return makeStepId(randomIdString(rng));
}

/** M6 — `PriceObservations` is append-only (DESIGN_PRODUCTS.md §2); every row mints its own id client-side, same as `EventId`. */
export function newPriceObservationId(rng: Rng): PriceObservationId {
  return makePriceObservationId(randomIdString(rng));
}

/** WP-PRODUCTS-MODEL re-key — a `Product`'s own identity, independent of any one barcode it is sold under. */
export function newProductId(rng: Rng): ProductId {
  return makeProductId(randomIdString(rng));
}
